/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package design.pattern.projet;

public class App {
    public String getGreeting() {
        Coffre coffre = new Coffre();
        System.out.println(coffre);
        Unite unite= new Unite(5, TypeUnite.MINEUR );
        System.out.println(unite);
        return "";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
